apiVersion: skaffold/v2beta6
kind: Config
metadata:
  name: syndesis
build:
  artifacts:
  - image: syndesis/syndesis-operator
    context: install/operator
    docker:
      dockerfile: build/Dockerfile
  # - image: syndesis/syndesis-meta
  #   context: install/operator/build
  # - image: syndesis/syndesis-server
  #   context: install/operator/build
  # - image: syndesis/syndesis-ui
  #   context: install/operator/build
deploy:
  kustomize:
    paths:
      - deploy/bases
  kubeContext: k3d-k3s-default

