---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./crds/syndesis.io_syndeses_crd.yaml
  - ./cluster_role.yaml
  - ./cluster_role_binding.yaml
  - ./role.yaml
  - ./role_binding.yaml
  - ./service_account.yaml
  - ./operator.yaml

