---
apiVersion: v1
kind: Secret
metadata:
  name: syndesis-oauth-credentials
stringData:
  OAUTH2_PROXY_PROVIDER: "${provider}"
  OAUTH2_PROXY_CLIENT_ID: "${client_id}"
  OAUTH2_PROXY_CLIENT_SECRET: "${client_secret}"
---
apiVersion: v1
kind: Secret
metadata:
  name: syndesis-oauth-comms
type: kubernetes.io/tls
data:
  tls.key: ${oauth_key}
  tls.crt: ${oauth_cert}
