name: Integration Tests for PR

on: pull_request

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build Syndesis
        run: tools/bin/syndesis build --backend --flash 
      - name: Run integration tests
        run: tools/bin/syndesis integration-test

